export const GET_SERIE_SUCCESS = 'GET_SERIE_SUCCESS';

export const SERIE_LOADING = 'SERIE_LOADING';
export const SERIE_LOADED = 'SERIE_LOADED';
export const SERIE_INVALID = 'SERIE_INVALID';

export const GET_GENRES_ERROR = 'GET_GENRES_ERROR';
export const GET_SERIES_BY_GENRE_SUCCESS = 'GET_SERIES_BY_GENRE_SUCCESS';
export const GET_SERIES_BY_GENRE_ERROR = 'GET_SERIES_BY_GENRE_ERROR';