export const MORE_CAST_LOADING = 'MORE_CAST_LOADING';
export const MORE_CAST_LOADED = 'MORE_CAST_LOADED';
export const GET_MORE_CAST = 'GET_MORE_CAST';

export const GET_DEFAULT_OPTIONS = 'GET_DEFAULT_OPTIONS';
export const ON_CHANGE_OPTION = 'ON_CHANGE_OPTION';
export const SET_OPTION_SELECTED = 'SET_OPTION_SELECTED';

export const SET_SEARCH_OBJECT = 'SET_SEARCH_OBJECT';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_SERIES_SUCCESS = 'FETCH_SERIES_SUCCESS';
export const FETCH_ACTORS_SUCCESS = 'FETCH_ACTORS_SUCCESS';

export const SET_BACKDROP_PATH = 'SET_BACKDROP_PATH';

export const HIDE_MEDIA_DETAILS = 'HIDE_MEDIA_DETAILS';