export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';

export const MOVIE_LOADING = 'MOVIE_LOADING';
export const MOVIE_LOADED = 'MOVIE_LOADED';
export const MOVIE_INVALID = 'MOVIE_INVALID';

export const GET_GENRES_ERROR = 'GET_GENRES_ERROR';
export const GET_MOVIES_BY_GENRE_SUCCESS = 'GET_MOVIES_BY_GENRE_SUCCESS';
export const GET_MOVIES_BY_GENRE_ERROR = 'GET_MOVIES_BY_GENRE_ERROR';