export const GET_LAST_RELEASED_MOVIES_SUCCESS = 'GET_LAST_RELEASED_MOVIES_SUCCESS';
export const GET_LAST_RELEASED_MOVIES_ERROR = 'GET_LAST_RELEASED_MOVIES_ERROR';

export const GET_POPULAR_SERIES_SUCCESS = 'GET_POPULAR_SERIES_SUCCESS';
export const GET_POPULAR_SERIES_ERROR = 'GET_POPULAR_SERIES_ERROR';

export const GET_POPULAR_ACTORS_SUCCESS = 'GET_POPULAR_ACTORS_SUCCESS';
export const GET_POPULAR_ACTORS_ERROR = 'GET_POPULAR_ACTORS_ERROR';