export const GET_ACTOR_SUCCESS = 'GET_ACTOR_SUCCESS';

export const ACTOR_LOADING = 'ACTOR_LOADING';
export const ACTOR_LOADED = 'ACTOR_LOADED';
export const ACTOR_INVALID = 'ACTOR_INVALID';

export const GET_POPULAR_ACTORS_SUCCESS = 'GET_POPULAR_ACTORS_SUCCESS';
export const GET_POPULAR_ACTORS_ERROR = 'GET_POPULAR_ACTORS_ERROR';